// AUTO-GENERATED by Seefar from the live Supabase schema — do not edit by hand.
// Every Supabase query in this app is type-checked against the fields below.
// If the schema changes, re-run the Supabase integration to refresh this file.

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export type Database = {
  // Allows to automatically instantiate createClient with right options
  // instead of createClient<Database, { PostgrestVersion: 'XX' }>(URL, KEY)
  __InternalSupabase: {
    PostgrestVersion: "14.5"
  }
  public: {
    Tables: {
      addresses: {
        Row: {
          apartment: string | null
          city: string | null
          created_at: string | null
          id: string
          instructions: string | null
          isDefault: boolean | null
          label: string | null
          latitude: number | null
          longitude: number | null
          street: string | null
          userId: string
          zipcode: string | null
        }
        Insert: {
          apartment?: string | null
          city?: string | null
          created_at?: string | null
          id?: string
          instructions?: string | null
          isDefault?: boolean | null
          label?: string | null
          latitude?: number | null
          longitude?: number | null
          street?: string | null
          userId: string
          zipcode?: string | null
        }
        Update: {
          apartment?: string | null
          city?: string | null
          created_at?: string | null
          id?: string
          instructions?: string | null
          isDefault?: boolean | null
          label?: string | null
          latitude?: number | null
          longitude?: number | null
          street?: string | null
          userId?: string
          zipcode?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "addresses_userId_fkey"
            columns: ["userId"]
            isOneToOne: false
            referencedRelation: "users"
            referencedColumns: ["id"]
          },
        ]
      }
      customization_options: {
        Row: {
          created_at: string | null
          customizationId: string
          id: string
          name: string
          price: number | null
        }
        Insert: {
          created_at?: string | null
          customizationId: string
          id?: string
          name: string
          price?: number | null
        }
        Update: {
          created_at?: string | null
          customizationId?: string
          id?: string
          name?: string
          price?: number | null
        }
        Relationships: [
          {
            foreignKeyName: "customization_options_customizationId_fkey"
            columns: ["customizationId"]
            isOneToOne: false
            referencedRelation: "customizations"
            referencedColumns: ["id"]
          },
        ]
      }
      customizations: {
        Row: {
          created_at: string | null
          id: string
          maxSelections: number | null
          menuItemId: string
          name: string
          required: boolean | null
        }
        Insert: {
          created_at?: string | null
          id?: string
          maxSelections?: number | null
          menuItemId: string
          name: string
          required?: boolean | null
        }
        Update: {
          created_at?: string | null
          id?: string
          maxSelections?: number | null
          menuItemId?: string
          name?: string
          required?: boolean | null
        }
        Relationships: [
          {
            foreignKeyName: "customizations_menuItemId_fkey"
            columns: ["menuItemId"]
            isOneToOne: false
            referencedRelation: "menu_items"
            referencedColumns: ["id"]
          },
        ]
      }
      drivers: {
        Row: {
          avatar: string | null
          created_at: string | null
          currentLatitude: number | null
          currentLongitude: number | null
          id: string
          licensePlate: string | null
          name: string
          phone: string | null
          rating: number | null
          status: string | null
          vehicle: string | null
        }
        Insert: {
          avatar?: string | null
          created_at?: string | null
          currentLatitude?: number | null
          currentLongitude?: number | null
          id?: string
          licensePlate?: string | null
          name: string
          phone?: string | null
          rating?: number | null
          status?: string | null
          vehicle?: string | null
        }
        Update: {
          avatar?: string | null
          created_at?: string | null
          currentLatitude?: number | null
          currentLongitude?: number | null
          id?: string
          licensePlate?: string | null
          name?: string
          phone?: string | null
          rating?: number | null
          status?: string | null
          vehicle?: string | null
        }
        Relationships: []
      }
      menu_items: {
        Row: {
          category: string | null
          created_at: string | null
          description: string | null
          id: string
          image: string | null
          isPopular: boolean | null
          name: string
          price: number | null
          restaurantId: string
        }
        Insert: {
          category?: string | null
          created_at?: string | null
          description?: string | null
          id?: string
          image?: string | null
          isPopular?: boolean | null
          name: string
          price?: number | null
          restaurantId: string
        }
        Update: {
          category?: string | null
          created_at?: string | null
          description?: string | null
          id?: string
          image?: string | null
          isPopular?: boolean | null
          name?: string
          price?: number | null
          restaurantId?: string
        }
        Relationships: [
          {
            foreignKeyName: "menu_items_restaurantId_fkey"
            columns: ["restaurantId"]
            isOneToOne: false
            referencedRelation: "restaurants"
            referencedColumns: ["id"]
          },
        ]
      }
      order_item_customizations: {
        Row: {
          created_at: string | null
          customizationId: string
          id: string
          optionIds: string[] | null
          orderItemId: string
        }
        Insert: {
          created_at?: string | null
          customizationId: string
          id?: string
          optionIds?: string[] | null
          orderItemId: string
        }
        Update: {
          created_at?: string | null
          customizationId?: string
          id?: string
          optionIds?: string[] | null
          orderItemId?: string
        }
        Relationships: [
          {
            foreignKeyName: "order_item_customizations_customizationId_fkey"
            columns: ["customizationId"]
            isOneToOne: false
            referencedRelation: "customizations"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "order_item_customizations_orderItemId_fkey"
            columns: ["orderItemId"]
            isOneToOne: false
            referencedRelation: "order_items"
            referencedColumns: ["id"]
          },
        ]
      }
      order_items: {
        Row: {
          created_at: string | null
          id: string
          menuItemId: string
          orderId: string
          quantity: number | null
          specialInstructions: string | null
          totalPrice: number | null
        }
        Insert: {
          created_at?: string | null
          id?: string
          menuItemId: string
          orderId: string
          quantity?: number | null
          specialInstructions?: string | null
          totalPrice?: number | null
        }
        Update: {
          created_at?: string | null
          id?: string
          menuItemId?: string
          orderId?: string
          quantity?: number | null
          specialInstructions?: string | null
          totalPrice?: number | null
        }
        Relationships: [
          {
            foreignKeyName: "order_items_menuItemId_fkey"
            columns: ["menuItemId"]
            isOneToOne: false
            referencedRelation: "menu_items"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "order_items_orderId_fkey"
            columns: ["orderId"]
            isOneToOne: false
            referencedRelation: "orders"
            referencedColumns: ["id"]
          },
        ]
      }
      orders: {
        Row: {
          created_at: string | null
          deliveryAddressId: string | null
          deliveryFee: number | null
          driverId: string | null
          estimatedDelivery: string | null
          id: string
          paymentMethodId: string | null
          rating: number | null
          restaurantId: string
          review: string | null
          serviceFee: number | null
          status: string | null
          subtotal: number | null
          tip: number | null
          totalPrice: number | null
          updated_at: string | null
          userId: string
        }
        Insert: {
          created_at?: string | null
          deliveryAddressId?: string | null
          deliveryFee?: number | null
          driverId?: string | null
          estimatedDelivery?: string | null
          id?: string
          paymentMethodId?: string | null
          rating?: number | null
          restaurantId: string
          review?: string | null
          serviceFee?: number | null
          status?: string | null
          subtotal?: number | null
          tip?: number | null
          totalPrice?: number | null
          updated_at?: string | null
          userId: string
        }
        Update: {
          created_at?: string | null
          deliveryAddressId?: string | null
          deliveryFee?: number | null
          driverId?: string | null
          estimatedDelivery?: string | null
          id?: string
          paymentMethodId?: string | null
          rating?: number | null
          restaurantId?: string
          review?: string | null
          serviceFee?: number | null
          status?: string | null
          subtotal?: number | null
          tip?: number | null
          totalPrice?: number | null
          updated_at?: string | null
          userId?: string
        }
        Relationships: [
          {
            foreignKeyName: "orders_deliveryAddressId_fkey"
            columns: ["deliveryAddressId"]
            isOneToOne: false
            referencedRelation: "addresses"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "orders_driverId_fkey"
            columns: ["driverId"]
            isOneToOne: false
            referencedRelation: "drivers"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "orders_paymentMethodId_fkey"
            columns: ["paymentMethodId"]
            isOneToOne: false
            referencedRelation: "payment_methods"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "orders_restaurantId_fkey"
            columns: ["restaurantId"]
            isOneToOne: false
            referencedRelation: "restaurants"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "orders_userId_fkey"
            columns: ["userId"]
            isOneToOne: false
            referencedRelation: "users"
            referencedColumns: ["id"]
          },
        ]
      }
      payment_methods: {
        Row: {
          brand: string | null
          created_at: string | null
          id: string
          isDefault: boolean | null
          last4: string | null
          type: string | null
          userId: string
        }
        Insert: {
          brand?: string | null
          created_at?: string | null
          id?: string
          isDefault?: boolean | null
          last4?: string | null
          type?: string | null
          userId: string
        }
        Update: {
          brand?: string | null
          created_at?: string | null
          id?: string
          isDefault?: boolean | null
          last4?: string | null
          type?: string | null
          userId?: string
        }
        Relationships: [
          {
            foreignKeyName: "payment_methods_userId_fkey"
            columns: ["userId"]
            isOneToOne: false
            referencedRelation: "users"
            referencedColumns: ["id"]
          },
        ]
      }
      restaurants: {
        Row: {
          address: string | null
          created_at: string | null
          cuisine: string | null
          deliveryFee: number | null
          deliveryTime: string | null
          id: string
          image: string | null
          latitude: number | null
          longitude: number | null
          minOrder: number | null
          name: string
          operatingHours: string | null
          phone: string | null
          rating: number | null
          reviewCount: number | null
        }
        Insert: {
          address?: string | null
          created_at?: string | null
          cuisine?: string | null
          deliveryFee?: number | null
          deliveryTime?: string | null
          id?: string
          image?: string | null
          latitude?: number | null
          longitude?: number | null
          minOrder?: number | null
          name: string
          operatingHours?: string | null
          phone?: string | null
          rating?: number | null
          reviewCount?: number | null
        }
        Update: {
          address?: string | null
          created_at?: string | null
          cuisine?: string | null
          deliveryFee?: number | null
          deliveryTime?: string | null
          id?: string
          image?: string | null
          latitude?: number | null
          longitude?: number | null
          minOrder?: number | null
          name?: string
          operatingHours?: string | null
          phone?: string | null
          rating?: number | null
          reviewCount?: number | null
        }
        Relationships: []
      }
      reviews: {
        Row: {
          comment: string | null
          created_at: string | null
          id: string
          orderId: string
          rating: number | null
          restaurantId: string
          userAvatar: string | null
          userId: string
          userName: string | null
        }
        Insert: {
          comment?: string | null
          created_at?: string | null
          id?: string
          orderId: string
          rating?: number | null
          restaurantId: string
          userAvatar?: string | null
          userId: string
          userName?: string | null
        }
        Update: {
          comment?: string | null
          created_at?: string | null
          id?: string
          orderId?: string
          rating?: number | null
          restaurantId?: string
          userAvatar?: string | null
          userId?: string
          userName?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "reviews_orderId_fkey"
            columns: ["orderId"]
            isOneToOne: false
            referencedRelation: "orders"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "reviews_restaurantId_fkey"
            columns: ["restaurantId"]
            isOneToOne: false
            referencedRelation: "restaurants"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "reviews_userId_fkey"
            columns: ["userId"]
            isOneToOne: false
            referencedRelation: "users"
            referencedColumns: ["id"]
          },
        ]
      }
      seefar_metadata: {
        Row: {
          app_id: string
          app_name: string
          created_at: string | null
          id: string
          seefar_origin: boolean | null
        }
        Insert: {
          app_id: string
          app_name: string
          created_at?: string | null
          id?: string
          seefar_origin?: boolean | null
        }
        Update: {
          app_id?: string
          app_name?: string
          created_at?: string | null
          id?: string
          seefar_origin?: boolean | null
        }
        Relationships: []
      }
      users: {
        Row: {
          avatar: string | null
          created_at: string | null
          defaultAddressId: string | null
          email: string | null
          id: string
          name: string | null
          phone: string | null
          referralCode: string | null
        }
        Insert: {
          avatar?: string | null
          created_at?: string | null
          defaultAddressId?: string | null
          email?: string | null
          id: string
          name?: string | null
          phone?: string | null
          referralCode?: string | null
        }
        Update: {
          avatar?: string | null
          created_at?: string | null
          defaultAddressId?: string | null
          email?: string | null
          id?: string
          name?: string | null
          phone?: string | null
          referralCode?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "fk_users_default_address"
            columns: ["defaultAddressId"]
            isOneToOne: false
            referencedRelation: "addresses"
            referencedColumns: ["id"]
          },
        ]
      }
    }
    Views: {
      [_ in never]: never
    }
    Functions: {
      [_ in never]: never
    }
    Enums: {
      [_ in never]: never
    }
    CompositeTypes: {
      [_ in never]: never
    }
  }
}

type DatabaseWithoutInternals = Omit<Database, "__InternalSupabase">

type DefaultSchema = DatabaseWithoutInternals[Extract<keyof Database, "public">]

export type Tables<
  DefaultSchemaTableNameOrOptions extends
    | keyof (DefaultSchema["Tables"] & DefaultSchema["Views"])
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
        DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
      DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])[TableName] extends {
      Row: infer R
    }
    ? R
    : never
  : DefaultSchemaTableNameOrOptions extends keyof (DefaultSchema["Tables"] &
        DefaultSchema["Views"])
    ? (DefaultSchema["Tables"] &
        DefaultSchema["Views"])[DefaultSchemaTableNameOrOptions] extends {
        Row: infer R
      }
      ? R
      : never
    : never

export type TablesInsert<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Insert: infer I
    }
    ? I
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Insert: infer I
      }
      ? I
      : never
    : never

export type TablesUpdate<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Update: infer U
    }
    ? U
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Update: infer U
      }
      ? U
      : never
    : never

export type Enums<
  DefaultSchemaEnumNameOrOptions extends
    | keyof DefaultSchema["Enums"]
    | { schema: keyof DatabaseWithoutInternals },
  EnumName extends DefaultSchemaEnumNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"]
    : never = never,
> = DefaultSchemaEnumNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"][EnumName]
  : DefaultSchemaEnumNameOrOptions extends keyof DefaultSchema["Enums"]
    ? DefaultSchema["Enums"][DefaultSchemaEnumNameOrOptions]
    : never

export type CompositeTypes<
  PublicCompositeTypeNameOrOptions extends
    | keyof DefaultSchema["CompositeTypes"]
    | { schema: keyof DatabaseWithoutInternals },
  CompositeTypeName extends PublicCompositeTypeNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"]
    : never = never,
> = PublicCompositeTypeNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"][CompositeTypeName]
  : PublicCompositeTypeNameOrOptions extends keyof DefaultSchema["CompositeTypes"]
    ? DefaultSchema["CompositeTypes"][PublicCompositeTypeNameOrOptions]
    : never

export const Constants = {
  public: {
    Enums: {},
  },
} as const
